cookie:
  expiry_days: 30
  key: random_signature_key_change_this_in_production
  name: expense_tracker_cookie
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$VeDlrIbQ/wFkyadrM0QPyuVnbUx7X8DCcdG//zmKWsgqrRLlsyvsi
